main: com.forgenz.horses.Horses
name: Horses
version: $(PROJECT_VERSION)
author: ShadowDog007
website: 'http://dev.bukkit.org/bukkit-plugins/horse-stables/'
softdepend: [Vault, NoCheatPlus]

commands:
  horses:
    description: Virtual Stables System main command
    aliases: [h, horse]

permissions:
  horses.vip:
    description: Gives the player special bonuses
    default: false
    
  horses.set.admin:
    default: op
    description: Give access to admin commands
    children:
      horses.set.user: true
      horses.command.give: true
      horses.command.reload: true

  horses.set.user:
    default: true
    description: Gives access to all player commands
    children:
      horses.command.list: true
      horses.command.dismiss: true
      horses.command.rename: true
      horses.command.summon: true
      horses.command.types: true
      horses.command.heal: true
      horses.command.buy: true
      horses.command.delete: true
      horses.colour: true
      
      horses.type.white: true
      horses.type.creamy: true
      horses.type.chestnut: true
      horses.type.brown: true
      horses.type.black: true
      horses.type.gray: true
      horses.type.darkbrown: true
  
      horses.type.blazewhite: true
      horses.type.blazecreamy: true
      horses.type.blazechestnut: true
      horses.type.blazebrown: true
      horses.type.blazeblack: true
      horses.type.blazegray: true
      horses.type.blazedarkbrown: true
  
      horses.type.paintwhite: true
      horses.type.paintcreamy: true
      horses.type.paintchestnut: true
      horses.type.paintbrown: true
      horses.type.paintblack: true
      horses.type.paintgray: true
      horses.type.paintdarkbrown: true
  
      horses.type.leopardwhite: true
      horses.type.leopardcreamy: true
      horses.type.leopardchestnut: true
      horses.type.leopardbrown: true
      horses.type.leopardblack: true
      horses.type.leopardgray: true
      horses.type.leoparddarkbrown: true
  
      horses.type.sootywhite: true
      horses.type.sootycreamy: true
      horses.type.sootychestnut: true
      horses.type.sootybrown: true
      horses.type.sootyblack: true
      horses.type.sootygray: true
      horses.type.sootydarkbrown: true
  
      horses.type.donkey: true
      horses.type.mule: true

  horses.command.list:
    description: Gives access to the /horses list command
  horses.command.dismiss:
    description: Gives access to the /horses dismiss command
  horses.command.rename:
    description: Gives access to the /horses rename command
  horses.command.summon:
    description: Gives access to the /horses summon command
  horses.command.types:
    description: Gives access to the /horses types command
  horses.command.heal:
    description: Gives access to the /horses heal command
  horses.command.buy:
    description: Gives access to the /horses buy command
  horses.command.delete:
    description: Gives access to the /horses delete command

  horses.command.give:
    description: Gives access to the /horses give command
  horses.command.reload:
    description: Gives access to the /horses reload command

  horses.colour: {description: 'Lets players use colour in their horses names'}
  horses.formattingcodes: {default: false , description: 'Lets players use formatting codes in their horses names'}
  
  horses.type.white: {}
  horses.type.creamy: {}
  horses.type.chestnut: {}
  horses.type.brown: {}
  horses.type.black: {}
  horses.type.gray: {}
  horses.type.darkbrown: {}
  
  horses.type.blazewhite: {}
  horses.type.blazecreamy: {}
  horses.type.blazechestnut: {}
  horses.type.blazebrown: {}
  horses.type.blazeblack: {}
  horses.type.blazegray: {}
  horses.type.blazedarkbrown: {}
  
  horses.type.paintwhite: {}
  horses.type.paintcreamy: {}
  horses.type.paintchestnut: {}
  horses.type.paintbrown: {}
  horses.type.paintblack: {}
  horses.type.paintgray: {}
  horses.type.paintdarkbrown: {}
  
  horses.type.leopardwhite: {}
  horses.type.leopardcreamy: {}
  horses.type.leopardchestnut: {}
  horses.type.leopardbrown: {}
  horses.type.leopardblack: {}
  horses.type.leopardgray: {}
  horses.type.leoparddarkbrown: {}
  
  horses.type.sootywhite: {}
  horses.type.sootycreamy: {}
  horses.type.sootychestnut: {}
  horses.type.sootybrown: {}
  horses.type.sootyblack: {}
  horses.type.sootygray: {}
  horses.type.sootydarkbrown: {}
  
  horses.type.donkey: {}
  horses.type.mule: {}
  horses.type.undead: {}
  horses.type.skeleton: {}